name: Build and Test .NET API

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout source
          uses: actions/checkout@v4

        - name: Set Up .NET SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.x'
        
        - name: Restore Dependencies
          run: dotnet restore
          
        - name: Build
          run: dotnet build --no-restore
